# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0005_auto_20161118_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='belong_to',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover',
        ),
        migrations.AddField(
            model_name='collection',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_collection', to='firstapp.Article'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('like', 'like'), ('normal', 'normal'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
