# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20161120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='你的真实姓名', max_length=20, null=True),
        ),
    ]
