# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0019_auto_20161121_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='for_article',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='for_user',
        ),
        migrations.AddField(
            model_name='collection',
            name='to_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_collection', to='firstapp.Article'),
        ),
        migrations.AddField(
            model_name='collection',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('like', 'like'), ('normal', 'normal'), ('dislike', 'dislike')], max_length=10),
        ),
    ]
