# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0020_auto_20161122_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='to_article',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='to_user',
        ),
        migrations.AddField(
            model_name='collection',
            name='article_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_collection', to='firstapp.Article'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
