# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20161122_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='article_collection',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user_collection',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('normal', 'normal'), ('dislike', 'dislike'), ('like', 'like')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
